before_script:
  - sudo wget http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list --output-document=/etc/apt/sources.list.d/medibuntu.list && sudo apt-get  -q update && sudo apt-get --yes -q --allow-unauthenticated install medibuntu-keyring && sudo apt-get -q update
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
language: node_js
node_js:
  - 0.8